[features]
seeds = false
skip-lint = false
[programs.localnet]
pdas = "9oXTjDJcDWYD8UQUX3CFNjH7sXzdWhf8dwwfAy4iu9C1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/cleberson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
